// flow-typed signature: 1e097dffe0f766d7ca0be7e89946c14a
// flow-typed version: <<STUB>>/mobx-state-tree_v3.10.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-state-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-state-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-state-tree/dist/core/action' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/flow' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/json-patch' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/mst-operations' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/node/BaseNode' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/node/create-node' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/node/Hook' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/node/identifier-cache' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/node/livelinessChecking' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/node/node-utils' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/node/object-node' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/node/scalar-node' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/process' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/type/type-checker' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/core/type/type' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/index' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/internal' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/middlewares/create-action-tracking-middleware' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/middlewares/on-action' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/mobx-state-tree' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/mobx-state-tree.module' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/mobx-state-tree.umd' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/complex-types/array' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/complex-types/map' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/complex-types/model' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/index' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/primitives' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/custom' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/enumeration' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/frozen' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/identifier' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/late' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/literal' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/maybe' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/optional' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/reference' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/refinement' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/types/utility-types/union' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-state-tree/dist/core/action.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/action'>;
}
declare module 'mobx-state-tree/dist/core/flow.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/flow'>;
}
declare module 'mobx-state-tree/dist/core/json-patch.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/json-patch'>;
}
declare module 'mobx-state-tree/dist/core/mst-operations.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/mst-operations'>;
}
declare module 'mobx-state-tree/dist/core/node/BaseNode.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/node/BaseNode'>;
}
declare module 'mobx-state-tree/dist/core/node/create-node.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/node/create-node'>;
}
declare module 'mobx-state-tree/dist/core/node/Hook.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/node/Hook'>;
}
declare module 'mobx-state-tree/dist/core/node/identifier-cache.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/node/identifier-cache'>;
}
declare module 'mobx-state-tree/dist/core/node/livelinessChecking.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/node/livelinessChecking'>;
}
declare module 'mobx-state-tree/dist/core/node/node-utils.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/node/node-utils'>;
}
declare module 'mobx-state-tree/dist/core/node/object-node.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/node/object-node'>;
}
declare module 'mobx-state-tree/dist/core/node/scalar-node.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/node/scalar-node'>;
}
declare module 'mobx-state-tree/dist/core/process.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/process'>;
}
declare module 'mobx-state-tree/dist/core/type/type-checker.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/type/type-checker'>;
}
declare module 'mobx-state-tree/dist/core/type/type.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/core/type/type'>;
}
declare module 'mobx-state-tree/dist/index.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/index'>;
}
declare module 'mobx-state-tree/dist/internal.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/internal'>;
}
declare module 'mobx-state-tree/dist/middlewares/create-action-tracking-middleware.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/middlewares/create-action-tracking-middleware'>;
}
declare module 'mobx-state-tree/dist/middlewares/on-action.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/middlewares/on-action'>;
}
declare module 'mobx-state-tree/dist/mobx-state-tree.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/mobx-state-tree'>;
}
declare module 'mobx-state-tree/dist/mobx-state-tree.module.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/mobx-state-tree.module'>;
}
declare module 'mobx-state-tree/dist/mobx-state-tree.umd.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/mobx-state-tree.umd'>;
}
declare module 'mobx-state-tree/dist/types/complex-types/array.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/complex-types/array'>;
}
declare module 'mobx-state-tree/dist/types/complex-types/map.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/complex-types/map'>;
}
declare module 'mobx-state-tree/dist/types/complex-types/model.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/complex-types/model'>;
}
declare module 'mobx-state-tree/dist/types/index.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/index'>;
}
declare module 'mobx-state-tree/dist/types/primitives.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/primitives'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/custom.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/custom'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/enumeration.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/enumeration'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/frozen.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/frozen'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/identifier.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/identifier'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/late.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/late'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/literal.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/literal'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/maybe.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/maybe'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/optional.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/optional'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/reference.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/reference'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/refinement.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/refinement'>;
}
declare module 'mobx-state-tree/dist/types/utility-types/union.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/types/utility-types/union'>;
}
declare module 'mobx-state-tree/dist/utils.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/utils'>;
}
