// flow-typed signature: f48f770783f1ced82158ac67175678e6
// flow-typed version: <<STUB>>/mst-middlewares_v3.10.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mst-middlewares'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mst-middlewares' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mst-middlewares/dist/action-logger' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/atomic' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/index' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/mst-middlewares' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/mst-middlewares.module' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/mst-middlewares.umd' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/redux' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/simple-action-logger' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/time-traveller' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/undo-manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mst-middlewares/dist/action-logger.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/action-logger'>;
}
declare module 'mst-middlewares/dist/atomic.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/atomic'>;
}
declare module 'mst-middlewares/dist/index.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/index'>;
}
declare module 'mst-middlewares/dist/mst-middlewares.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/mst-middlewares'>;
}
declare module 'mst-middlewares/dist/mst-middlewares.module.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/mst-middlewares.module'>;
}
declare module 'mst-middlewares/dist/mst-middlewares.umd.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/mst-middlewares.umd'>;
}
declare module 'mst-middlewares/dist/redux.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/redux'>;
}
declare module 'mst-middlewares/dist/simple-action-logger.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/simple-action-logger'>;
}
declare module 'mst-middlewares/dist/time-traveller.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/time-traveller'>;
}
declare module 'mst-middlewares/dist/undo-manager.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/undo-manager'>;
}
